name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - uses: jitterbit/get-changed-files@v1
      id: list_changes
      with:
        format: space-delimited
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for Dockerfile changes
      id: dockerfile_changes
      run: |
        files="${{ steps.list_changes.outputs.modified }}"
        changed=FALSE
        for file in $files
        do
            if [[ "$file" == "dd_agent/Dockerfile" ]]; then
                changed=TRUE
                break
            fi
        done
        echo "changed=$changed" >> $GITHUB_OUTPUT

    - name: Get version from VERSION.md
      id: version
      run: echo "version=$(cat dd_agent/VERSION.md)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      if: steps.dockerfile_changes.outputs.changed == 'TRUE'
      run: docker buildx build --file dd_agent/Dockerfile -t docker.pkg.github.com/${{ github.repository }}/dd_agent:${{ steps.version.outputs.version }} .

    - name: Log in to GitHub Container Registry
      if: steps.dockerfile_changes.outputs.changed == 'TRUE'
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Container Registry
      if: steps.dockerfile_changes.outputs.changed == 'TRUE'
      run: docker push docker.pkg.github.com/${{ github.repository }}/dd_agent:${{ steps.version.outputs.version }}
